import re

EPOCHS = 50
IMAGE_LENGTH = 256
IMAGE_DEPTH = 3
NUM_IMAGES = 26756

BATCH_SIZE = 4
KERNEL_SIZE = 2
STRIDE_SIZE = 2

NUM_ENCODER_CHANNELS = 64
# NUM_Z_CHANNELS = 512
NUM_Z_CHANNELS = 512
NUM_GEN_CHANNELS = 1024
MULTISTYLE_Z_SHAPE = (11, 512)
RESNET_TYPE = 18


# NUM_AGES = 10
NUM_AGES = 7
NUM_GENDERS = 2
LABEL_LEN = NUM_AGES + NUM_GENDERS
NUM_GENDERS_EXPANDED = NUM_GENDERS * (NUM_AGES // NUM_GENDERS)
# LABEL_LEN_EXPANDED = NUM_AGES + NUM_GENDERS_EXPANDED
LABEL_LEN_EXPANDED = NUM_AGES + NUM_GENDERS
# FAW_LENGTH = 512 + NUM_GENDERS
FAW_LENGTH = 512 


MALE = 0
FEMALE = 1

UTKFACE_DEFAULT_PATH = "./data/UTKFace"
UTKFACE_ORIGINAL_IMAGE_FORMAT = re.compile("^(\d+)_(\d+)_\d+_(\d+)\.jpg\.chip\.jpg$")

TRAINED_MODEL_EXT = ".pt"
TRAINED_MODEL_FORMAT = "{}" + TRAINED_MODEL_EXT